---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.py"
  - "**.rb"
exclude_paths:
  - app/comic/core/static/**/*
  - app/comic/**/migrations/**/*
  - app/tests/core_tests/resources/**/*
