tasks:
    - init: echo "Replace me with a build script for the project."
      command: /usr/lib/postgresql/10/bin/postgres -D /var/lib/postgresql/10/main -c config_file=/etc/postgresql/10/main/postgresql.conf
  image:
    file: .gitpod.Dockerfile
  