tasks:
    - init: |
            wget -O - https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh | sh &&
            conda create -n comic python=3 &&
            conda activate comic &&
            pip3 install -r requirements.txt && pip3 install -r requirements.dev.txt &&
            pip3 install -e app &&
            cp .env.dev .env &&
            cd app &&
            python manage.py migrate && 
            python manage.py init_db_data
image:
    file: .gitpod.Dockerfile
  