tasks:
    - init: |
            cp .env.dev .env &&
            conda activate comic &&
            createuser --superuser comic &&
            createdb -O comic comic &&
            pip install -e app &&
            cd app &&
            python manage.py migrate &&
            python manage.py init_db_data

image:
    file: .gitpod.Dockerfile

vscode:
    extensions:
        - ms-python.python@2020.2.64397:hwGBCETiS+304zeJTipEhQ==