sudo: required

language: python

python:
  - 3.6

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

services:
  - postgresql

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pipenv

env:
  global:
    - POSTGRES_DB=comic
    - POSTGRES_HOST=127.0.0.1
    - POSTGRES_PASSWORD=comic
    - POSTGRES_USER=comic
    - POSTGRES_PORT=5433

before_install:
  - sudo -u postgres psql -c "CREATE DATABASE $POSTGRES_DB;" --host=$POSTGRES_HOST --port=$POSTGRES_PORT -U postgres
  - sudo -u postgres psql -c "CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';" --host=$POSTGRES_HOST --port=$POSTGRES_PORT -U postgres
  - pg_isready --host=$POSTGRES_HOST --port=$POSTGRES_PORT --username=$POSTGRES_USER
  - pip install codecov pytest-cov
  - sudo mkdir -p /tmp/coverage
  - sudo chmod a+w /tmp/coverage

install:
  - pip install pipenv
  - pipenv install --dev

#install:
#  - make build
#  - docker-compose up -d

script:
#  - docker-compose run -v /tmp/coverage:/tmp/coverage web bash -c "COVERAGE_FILE=/tmp/coverage/.coverage pytest --cov-report= --cov=."
  - cd app
  - pytest

after_success:
#  - mv /tmp/coverage/.coverage .coverage.docker
#  - coverage combine
#  - codecov

deploy:
#  - provider: script
#    script: bash -c "docker login -u grandchallenge -p "$DOCKER_PASSWORD" && make push"
#    on:
#      all_branches: true
#      condition: $TRAVIS_BRANCH =~ ^master|eyra-master|staging$
