dist: xenial   # required for Python >= 3.7

sudo: required

language: python

python:
  - "3.6"
  - "3.7"

services:
  - docker

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - POSTGRES_DB=comic
    - POSTGRES_HOST=127.0.0.1
    - POSTGRES_PASSWORD=comic
    - POSTGRES_USER=comic
    - POSTGRES_PORT=5432

before_install:
  - sudo service postgresql stop
  - docker run -d -p $POSTGRES_PORT:5432 -e POSTGRES_DB=$POSTGRES_DB -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD postgres:10.4
  - pip install codecov pytest-cov
  - sudo mkdir -p /tmp/coverage
  - sudo chmod a+w /tmp/coverage

install:
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt

before_script:
  - |
    RETRIES=10
    until pg_isready --host=$POSTGRES_HOST --port=$POSTGRES_PORT --username=$POSTGRES_USER --timeout=1 || [ $RETRIES -eq 0 ]; do
        RETRIES=$((RETRIES-1))
        sleep 1
    done

script:
  - pytest app

after_success:
  - docker build . -t eyra/comic:latest -t eyra/comic:$TRAVIS_BUILD_NUMBER

deploy:
  - provider: script
    script: bash -c "docker login -u eyrabenchmark1 -p $DOCKER_PASSWORD && docker push eyra/comic:$TRAVIS_BUILD_NUMBER && docker push eyra/comic:latest"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master$
