sudo: required

services:
  - postgresql

language: python

python:
  - 3.6

env:
  global:
    - POSTGRES_DB=comic
    - POSTGRES_HOST=localhost
    - POSTGRES_PASSWORD=
    - POSTGRES_USER=postgres


before_install:
  - pip install codecov pytest-cov
  - sudo mkdir -p /tmp/coverage
  - sudo chmod a+w /tmp/coverage

install:
  - pip install pipenv
  - pipenv install --dev

#install:
#  - make build
#  - docker-compose up -d

script:
#  - docker-compose run -v /tmp/coverage:/tmp/coverage web bash -c "COVERAGE_FILE=/tmp/coverage/.coverage pytest --cov-report= --cov=."
  - cd app
  - pytest

after_success:
#  - mv /tmp/coverage/.coverage .coverage.docker
#  - coverage combine
#  - codecov

deploy:
#  - provider: script
#    script: bash -c "docker login -u grandchallenge -p "$DOCKER_PASSWORD" && make push"
#    on:
#      all_branches: true
#      condition: $TRAVIS_BRANCH =~ ^master|eyra-master|staging$
