sudo: required

language: python

python:
  - 3.6

services:
  - docker

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pipenv

env:
  global:
    - POSTGRES_DB=comic
    - POSTGRES_HOST=127.0.0.1
    - POSTGRES_PASSWORD=comic
    - POSTGRES_USER=comic
    - POSTGRES_PORT=5432

before_install:
  - sudo service postgresql stop
  - docker run -d -p $POSTGRES_PORT:5432 -e POSTGRES_DB=$POSTGRES_DB -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD postgres:10.4
  - pg_isready --host=$POSTGRES_HOST --port=$POSTGRES_PORT --username=$POSTGRES_USER --timeout=120
  - pip install codecov pytest-cov
  - sudo mkdir -p /tmp/coverage
  - sudo chmod a+w /tmp/coverage

install:
  - pip install pipenv
  - pipenv install --dev

#install:
#  - make build
#  - docker-compose up -d

script:
#  - docker-compose run -v /tmp/coverage:/tmp/coverage web bash -c "COVERAGE_FILE=/tmp/coverage/.coverage pytest --cov-report= --cov=."
  - cd app
  - pytest

after_success:
#  - mv /tmp/coverage/.coverage .coverage.docker
#  - coverage combine
#  - codecov

deploy:
#  - provider: script
#    script: bash -c "docker login -u grandchallenge -p "$DOCKER_PASSWORD" && make push"
#    on:
#      all_branches: true
#      condition: $TRAVIS_BRANCH =~ ^master|eyra-master|staging$
